sudo: false
language: node_js

node_js:
- "6"

# before_install:
#  - cd to your src if needed

before_script:  # turn off screen
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 2 # give xvfb some time to start

addons:
  firefox: "latest"

notifications:
  email: false
